import type { Metadata } from "next";
import {JetBrains_Mono } from "next/font/google";
import "./globals.css";
import NavBarTemplate from "@/components/templates/NavBarTemplate";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={jetbrains.className}>
      <body>
        <NavBarTemplate/>
        {children}
      </body>
    </html>
  );
}
